import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState, useEffect } from "react";
import { toast } from "sonner";
import {
  getComplaintById,
  getComplaintUpdates,
  updateComplaintStatus,
  generateAiResolutionDraft,
  submitCsatRating,
  addComplaintComment,
} from "@/lib/complaints.functions";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  ArrowLeft,
  Sparkles,
  Clock,
  ShieldCheck,
  User,
  MessageSquare,
  CheckCircle2,
  AlertCircle,
  Save,
  Loader2,
  Copy,
  Check,
  Tag,
  Star,
  Printer,
  Send,
  Mail,
  FileText,
  Info,
} from "lucide-react";
import {
  CATEGORY_LABEL,
  PRIORITY_LABEL,
  STATUS_LABEL,
  formatDate,
  priorityBadgeClass,
  statusBadgeClass,
} from "@/lib/format";

export const Route = createFileRoute("/_authenticated/complaints/$id")({
  component: ComplaintDetail,
});

const STATUSES = ["open", "in_progress", "resolved", "closed"] as const;

function ComplaintDetail() {
  const { id } = Route.useParams();
  const { user } = Route.useRouteContext();
  const queryClient = useQueryClient();
  const isAdmin = user.role === "admin";

  const [statusNote, setStatusNote] = useState("");
  const [selectedStatus, setSelectedStatus] = useState<string>("");
  const [updating, setUpdating] = useState(false);
  const [generatingDraft, setGeneratingDraft] = useState(false);
  const [copied, setCopied] = useState(false);

  // CSAT state
  const [csatRating, setCsatRating] = useState<number>(0);
  const [csatFeedback, setCsatFeedback] = useState("");
  const [submittingCsat, setSubmittingCsat] = useState(false);
  const [csatSubmitted, setCsatSubmitted] = useState(false);

  // Follow-up comment state
  const [newComment, setNewComment] = useState("");
  const [submittingComment, setSubmittingComment] = useState(false);

  const fetchComplaint = useServerFn(getComplaintById);
  const fetchUpdates = useServerFn(getComplaintUpdates);
  const doUpdateStatus = useServerFn(updateComplaintStatus);
  const doGenerateDraft = useServerFn(generateAiResolutionDraft);
  const doSubmitCsat = useServerFn(submitCsatRating);
  const doAddComment = useServerFn(addComplaintComment);

  const { data: complaint, isLoading } = useQuery({
    queryKey: ["complaint", id],
    queryFn: () => fetchComplaint({ data: { id } }),
  });

  const { data: updates } = useQuery({
    queryKey: ["complaint-updates", id],
    queryFn: () => fetchUpdates({ data: { complaintId: id } }),
    enabled: !!complaint,
  });

  useEffect(() => {
    if (complaint?.status) {
      setSelectedStatus(complaint.status);
    }
    if (complaint?.csatRating) {
      setCsatRating(complaint.csatRating);
      setCsatSubmitted(true);
    }
  }, [complaint?.status, complaint?.csatRating]);

  async function handleSaveStatus(e?: React.FormEvent) {
    if (e) e.preventDefault();
    const targetStatus = (selectedStatus || complaint?.status || "open") as (typeof STATUSES)[number];

    setUpdating(true);
    try {
      await doUpdateStatus({
        data: {
          complaintId: id,
          status: targetStatus,
          note: statusNote.trim() || undefined,
        },
      });
      toast.success(`Status updated to ${STATUS_LABEL[targetStatus] ?? targetStatus} with audit note saved!`);
      setStatusNote("");
      queryClient.invalidateQueries({ queryKey: ["complaint", id] });
      queryClient.invalidateQueries({ queryKey: ["complaint-updates", id] });
      queryClient.invalidateQueries({ queryKey: ["my-complaints"] });
      queryClient.invalidateQueries({ queryKey: ["all-complaints"] });
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to update complaint status");
    } finally {
      setUpdating(false);
    }
  }

  // ✨ Feature 1: Gemini AI Auto-Draft Resolution Reply
  async function handleGenerateAiDraft() {
    if (!complaint) return;
    setGeneratingDraft(true);
    try {
      const res = await doGenerateDraft({
        data: {
          title: complaint.title,
          description: complaint.description,
          category: complaint.category,
          customerName: complaint.userName || "Customer",
        },
      });
      if (res?.draft) {
        setStatusNote(res.draft);
        toast.success("AI draft generated by Google Gemini!");
      }
    } catch {
      toast.error("Failed to generate AI draft");
    } finally {
      setGeneratingDraft(false);
    }
  }

  // ⭐ Feature 2: Submit CSAT Rating
  async function handleCsatSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (csatRating === 0) {
      return toast.error("Please click a star rating (1 to 5) before submitting.");
    }
    setSubmittingCsat(true);
    try {
      await doSubmitCsat({
        data: {
          complaintId: id,
          rating: csatRating,
          feedback: csatFeedback.trim() || undefined,
        },
      });
      setCsatSubmitted(true);
      toast.success("Thank you for your rating and feedback! ⭐");
      queryClient.invalidateQueries({ queryKey: ["complaint", id] });
    } catch {
      toast.error("Failed to submit rating");
    } finally {
      setSubmittingCsat(false);
    }
  }

  // 💬 Feature 5: Add Live Follow-up Comment
  async function handleAddComment(e: React.FormEvent) {
    e.preventDefault();
    if (!newComment.trim()) return;
    setSubmittingComment(true);
    try {
      await doAddComment({
        data: {
          complaintId: id,
          message: newComment.trim(),
        },
      });
      setNewComment("");
      toast.success("Message posted to ticket thread!");
      queryClient.invalidateQueries({ queryKey: ["complaint-updates", id] });
    } catch {
      toast.error("Failed to post message");
    } finally {
      setSubmittingComment(false);
    }
  }

  // 📄 Feature 3: Export Resolution PDF / Print Certificate
  function handlePrintCertificate() {
    window.print();
  }

  function copyTicketId() {
    if (typeof navigator !== "undefined" && navigator.clipboard) {
      navigator.clipboard.writeText(id);
      setCopied(true);
      toast.success("Ticket ID copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    }
  }

  if (isLoading) {
    return (
      <div className="mx-auto max-w-4xl space-y-4">
        <div className="h-6 w-32 animate-pulse rounded-md bg-muted" />
        <div className="h-64 animate-pulse rounded-2xl bg-muted" />
      </div>
    );
  }

  if (!complaint) {
    return (
      <div className="mx-auto max-w-xl text-center py-16">
        <AlertCircle className="h-10 w-10 text-destructive mx-auto mb-3" />
        <h2 className="text-xl font-bold">Complaint Not Found</h2>
        <p className="text-sm text-muted-foreground mt-1">
          This ticket may have been removed or you do not have permission to view it.
        </p>
        <Link to="/dashboard" className="mt-5 inline-block">
          <Button variant="outline">Back to Dashboard</Button>
        </Link>
      </div>
    );
  }

  const isResolvedOrClosed = complaint.status === "resolved" || complaint.status === "closed";

  return (
    <div className="mx-auto max-w-4xl space-y-6 animate-fade-in-up pb-16">
      {/* Back button & Action Header */}
      <div className="flex items-center justify-between no-print">
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Dashboard
        </Link>

        <div className="flex items-center gap-2">
          {/* Feature 3: Export PDF / Print Certificate */}
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrintCertificate}
            className="text-xs font-semibold h-8"
          >
            <Printer className="mr-1.5 h-3.5 w-3.5" /> Export PDF / Print
          </Button>

          <button
            onClick={copyTicketId}
            className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground font-mono bg-muted/60 hover:bg-muted px-2.5 py-1 rounded-lg border border-border/50 transition-colors"
          >
            {copied ? <Check className="h-3 w-3 text-success" /> : <Copy className="h-3 w-3" />}
            <span>ID: {complaint.id}</span>
          </button>
        </div>
      </div>

      {/* Main Ticket Information Card */}
      <Card className="border-border/70 shadow-sm overflow-hidden bg-card/90 backdrop-blur-md">
        <CardHeader className="border-b border-border/50 bg-muted/20 pb-5">
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
            <div className="space-y-2">
              <CardTitle className="text-xl sm:text-2xl font-extrabold tracking-tight">
                {complaint.title}
              </CardTitle>

              {/* Submitter & Timestamp Credentials */}
              <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                <span className="flex items-center gap-1.5 font-medium text-foreground/90">
                  <User className="h-3.5 w-3.5 text-primary" />
                  <span>Submitted by: <b>{complaint.userName || "Customer"}</b> ({complaint.userEmail || "customer@example.com"})</span>
                </span>
                <span>•</span>
                <span className="flex items-center gap-1.5">
                  <Clock className="h-3.5 w-3.5" /> {formatDate(complaint.createdAt)}
                </span>
                {complaint.aiClassified && (
                  <>
                    <span>•</span>
                    <span className="inline-flex items-center gap-1 text-primary font-semibold">
                      <Sparkles className="h-3 w-3" /> Auto-Triaged by Gemini AI
                    </span>
                  </>
                )}
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-2 shrink-0">
              <Badge variant="outline" className="text-xs font-semibold capitalize bg-background">
                {CATEGORY_LABEL[complaint.category] ?? complaint.category}
              </Badge>
              <Badge variant="outline" className={`text-xs font-semibold capitalize ${priorityBadgeClass(complaint.priority)}`}>
                {PRIORITY_LABEL[complaint.priority] ?? complaint.priority}
              </Badge>
              <Badge variant="outline" className={`text-xs font-semibold capitalize ${statusBadgeClass(complaint.status)}`}>
                {STATUS_LABEL[complaint.status] ?? complaint.status}
              </Badge>
            </div>
          </div>
        </CardHeader>

        <CardContent className="pt-6 space-y-6">
          {/* Issue Description */}
          <div>
            <div className="mb-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Complaint Description
            </div>
            <div className="rounded-xl border border-border/60 bg-muted/30 p-4 text-sm leading-relaxed whitespace-pre-wrap">
              {complaint.description}
            </div>
          </div>

          {/* AI Reason Card */}
          {complaint.aiReason && (
            <div className="rounded-xl border border-primary/25 bg-primary/5 p-4 space-y-1.5">
              <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary">
                <Sparkles className="h-3.5 w-3.5" /> AI Triage Assessment (Google Gemini)
              </div>
              <p className="text-xs sm:text-sm text-foreground/90 leading-relaxed font-medium">
                {complaint.aiReason}
              </p>
            </div>
          )}

          {/* Admin Status Management & Feature 1 (AI Draft) */}
          {isAdmin ? (
            <div className="rounded-2xl border border-border/80 bg-accent/20 p-5 sm:p-6 space-y-4 no-print">
              <div className="flex items-center justify-between border-b border-border/40 pb-3">
                <div className="flex items-center gap-2 font-bold text-sm">
                  <ShieldCheck className="h-4.5 w-4.5 text-primary" /> Admin Actions: Update Status & Log Audit Note
                </div>
                <Badge variant="outline" className="text-[10px] uppercase font-bold bg-primary/10 text-primary border-primary/30">
                  Admin Control
                </Badge>
              </div>

              <form onSubmit={handleSaveStatus} className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-3">
                  {/* Select Status */}
                  <div className="space-y-1.5 sm:col-span-1">
                    <Label htmlFor="status-select" className="text-xs font-bold">
                      Set New Status
                    </Label>
                    <Select
                      value={selectedStatus}
                      onValueChange={(v) => setSelectedStatus(v)}
                      disabled={updating}
                    >
                      <SelectTrigger id="status-select" className="bg-background font-semibold text-xs h-10">
                        <SelectValue placeholder="Select Status" />
                      </SelectTrigger>
                      <SelectContent>
                        {STATUSES.map((s) => (
                          <SelectItem key={s} value={s} className="text-xs font-semibold">
                            {STATUS_LABEL[s]}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  {/* Resolution Note & AI Draft Button */}
                  <div className="space-y-1.5 sm:col-span-2">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="status-note" className="text-xs font-bold">
                        Resolution / Audit Note (Saved to Database)
                      </Label>
                      {/* ✨ Feature 1: AI Auto-Draft Resolution Reply */}
                      <button
                        type="button"
                        onClick={handleGenerateAiDraft}
                        disabled={generatingDraft}
                        className="inline-flex items-center gap-1 text-[11px] font-bold text-primary hover:text-primary/80 transition-colors"
                      >
                        <Sparkles className="h-3 w-3" />
                        {generatingDraft ? "Drafting with AI…" : "✨ Draft with Gemini AI"}
                      </button>
                    </div>
                    <Textarea
                      id="status-note"
                      value={statusNote}
                      onChange={(e) => setStatusNote(e.target.value)}
                      rows={2}
                      placeholder="e.g., Refund processed via Stripe gateway. Ticket marked resolved."
                      className="bg-background text-xs resize-none"
                      disabled={updating}
                    />
                  </div>
                </div>

                {/* Dedicated Save & Update Button */}
                <div className="flex justify-end pt-1">
                  <Button
                    type="submit"
                    disabled={updating || (selectedStatus === complaint.status && !statusNote.trim())}
                    className="font-bold shadow-sm hover:shadow-glow-sm transition-all h-10 px-6 text-xs"
                  >
                    {updating ? (
                      <span className="flex items-center gap-2">
                        <Loader2 className="h-3.5 w-3.5 animate-spin" /> Saving Changes…
                      </span>
                    ) : (
                      <span className="flex items-center gap-2">
                        <Save className="h-3.5 w-3.5" /> Update Status & Save Note
                      </span>
                    )}
                  </Button>
                </div>
              </form>
            </div>
          ) : (
            <div className="rounded-xl border border-border/60 bg-muted/20 p-4 text-xs text-muted-foreground flex items-center gap-2 no-print">
              <Clock className="h-4 w-4 text-primary shrink-0" />
              <span>
                Our support team is actively reviewing your ticket. Updates and resolutions will be logged in the timeline below and emailed to <b>{complaint.userEmail}</b>.
              </span>
            </div>
          )}

          {/* ⭐ Feature 2: Customer Satisfaction (CSAT) Rating Card */}
          {!isAdmin && isResolvedOrClosed && (
            <div className="rounded-2xl border border-success/30 bg-success/5 p-5 space-y-3 no-print">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 font-bold text-sm text-success">
                  <CheckCircle2 className="h-4.5 w-4.5" /> Rate Your Support Experience (CSAT)
                </div>
                {csatSubmitted && (
                  <Badge variant="outline" className="bg-success/10 text-success border-success/30 text-xs">
                    Rating Saved
                  </Badge>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                How satisfied were you with the speed and resolution of your ticket?
              </p>

              <form onSubmit={handleCsatSubmit} className="space-y-3 pt-1">
                {/* 5-Star Interactive Rating Selector */}
                <div className="flex items-center gap-1.5">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <button
                      key={star}
                      type="button"
                      disabled={csatSubmitted}
                      onClick={() => setCsatRating(star)}
                      className={`p-1 text-lg transition-transform hover:scale-125 ${
                        star <= csatRating ? "text-amber-400 fill-amber-400" : "text-muted-foreground/40"
                      }`}
                    >
                      ★
                    </button>
                  ))}
                  <span className="text-xs font-semibold text-muted-foreground ml-2">
                    {csatRating === 5
                      ? "Excellent 🎉"
                      : csatRating === 4
                      ? "Good 👍"
                      : csatRating === 3
                      ? "Average 😐"
                      : csatRating === 2
                      ? "Poor 👎"
                      : csatRating === 1
                      ? "Very Poor 😞"
                      : "Select stars"}
                  </span>
                </div>

                {!csatSubmitted && (
                  <>
                    <Input
                      value={csatFeedback}
                      onChange={(e) => setCsatFeedback(e.target.value)}
                      placeholder="Optional feedback: tell us what went well or could be improved…"
                      className="text-xs bg-background"
                      maxLength={400}
                    />
                    <div className="flex justify-end">
                      <Button
                        type="submit"
                        disabled={submittingCsat || csatRating === 0}
                        size="sm"
                        className="text-xs font-bold bg-success hover:bg-success/90 text-success-foreground h-8 px-4"
                      >
                        {submittingCsat ? "Saving Rating…" : "Submit Feedback ⭐"}
                      </Button>
                    </div>
                  </>
                )}
              </form>
            </div>
          )}
        </CardContent>
      </Card>

      {/* 💬 Feature 5: In-Ticket Discussion & Follow-up Thread */}
      <Card className="border-border/70 shadow-sm bg-card/90 no-print">
        <CardHeader className="border-b border-border/50 pb-3">
          <CardTitle className="text-sm font-bold flex items-center gap-2">
            <MessageSquare className="h-4 w-4 text-primary" /> Discussion & Follow-up Messages
          </CardTitle>
          <CardDescription className="text-xs">
            Send direct follow-up replies or questions regarding this ticket.
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-4 space-y-4">
          <form onSubmit={handleAddComment} className="flex gap-2">
            <Input
              value={newComment}
              onChange={(e) => setNewComment(e.target.value)}
              placeholder={
                isAdmin
                  ? "Post a message or question to the customer…"
                  : "Post an update or follow-up note for the support team…"
              }
              className="text-xs bg-background"
              disabled={submittingComment}
            />
            <Button
              type="submit"
              size="sm"
              disabled={submittingComment || !newComment.trim()}
              className="font-bold text-xs shrink-0"
            >
              <Send className="mr-1.5 h-3.5 w-3.5" /> Post
            </Button>
          </form>
        </CardContent>
      </Card>

      {/* Activity Timeline */}
      <Card className="border-border/70 shadow-sm bg-card/90">
        <CardHeader className="border-b border-border/50 pb-4">
          <div className="flex items-center justify-between">
            <CardTitle className="text-base font-bold flex items-center gap-2">
              <Clock className="h-4 w-4 text-primary" /> Activity & Audit Log
            </CardTitle>
            <span className="text-xs text-muted-foreground font-medium">
              {updates?.length ?? 0} {updates?.length === 1 ? "event" : "events"} recorded
            </span>
          </div>
        </CardHeader>
        <CardContent className="pt-6">
          {!updates || updates.length === 0 ? (
            <div className="text-center py-8 text-xs text-muted-foreground">
              No status changes recorded yet. When an admin updates this ticket, the audit history will appear here.
            </div>
          ) : (
            <ol className="relative border-l-2 border-border/80 ml-3 space-y-6 py-2">
              {updates.map((u) => (
                <li key={u.id} className="ml-6 space-y-1.5">
                  <div className="absolute -left-2.25 mt-1.5 h-4 w-4 rounded-full border-2 border-background bg-primary shadow-sm" />
                  <div className="flex flex-wrap items-center gap-2 text-xs sm:text-sm font-semibold">
                    {u.fromStatus || u.toStatus ? (
                      <>
                        <span>Status updated</span>
                        {u.fromStatus && (
                          <span className="text-muted-foreground font-normal">
                            from <b className="text-foreground">{STATUS_LABEL[u.fromStatus] ?? u.fromStatus}</b>
                          </span>
                        )}
                        <span>
                          to <b className="text-primary">{u.toStatus ? (STATUS_LABEL[u.toStatus] ?? u.toStatus) : "—"}</b>
                        </span>
                      </>
                    ) : (
                      <span className="text-foreground">Message logged</span>
                    )}
                    {u.authorName && (
                      <span className="text-xs text-muted-foreground font-normal">
                        by <b>{u.authorName}</b>
                      </span>
                    )}
                  </div>
                  {u.note && (
                    <div className="rounded-xl border border-primary/20 bg-muted/60 p-3 text-xs text-foreground mt-2 leading-relaxed">
                      "{u.note}"
                    </div>
                  )}
                  <div className="text-[11px] text-muted-foreground pt-0.5">
                    {formatDate(u.createdAt)}
                  </div>
                </li>
              ))}
            </ol>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
